# Generated by Django 5.0.2 on 2024-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20, null=True),
        ),
    ]
