# Generated by Django 5.0.2 on 2024-03-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0005_rename_type_category_product_type_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
