# Generated by Django 5.0.2 on 2024-03-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0013_remove_order_address_remove_order_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='user',
        ),
    ]
