# Generated by Django 5.0.2 on 2024-03-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0015_rename_user_order_customer_order_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
