# Generated by Django 5.0.2 on 2024-03-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0016_rename_full_name_order_shipping_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='customer',
        ),
    ]
