# Generated by Django 5.0.2 on 2024-03-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0019_orderitem_seller_userprofile_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
