# Generated by Django 5.0.2 on 2024-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0020_rename_seller_orderitem_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='earning',
            field=models.IntegerField(default=0),
        ),
    ]
