# Generated by Django 5.0.2 on 2024-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0022_remove_userprofile_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='earning',
            field=models.IntegerField(default=0),
        ),
    ]
