# Generated by Django 5.0.2 on 2024-04-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0026_alter_userprofile_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='approved',
        ),
    ]
