# Generated by Django 5.0.2 on 2024-04-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0028_userprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
