# Generated by Django 5.0.2 on 2024-04-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0029_product_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
