# Generated by Django 5.0.2 on 2024-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0030_delete_account_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
